// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVVrpDlwkbN4zn1OXfx611JV_UcoM5684',
    appId: '1:625640348358:web:c69c462f766f92e02b55c7',
    messagingSenderId: '625640348358',
    projectId: 'applacanasta',
    authDomain: 'applacanasta.firebaseapp.com',
    storageBucket: 'applacanasta.appspot.com',
    measurementId: 'G-2W9HQL26RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgNZTxnsQkRE1xVGMVBHAj4ZrrFTMnvZ0',
    appId: '1:625640348358:android:cf080574204729c22b55c7',
    messagingSenderId: '625640348358',
    projectId: 'applacanasta',
    storageBucket: 'applacanasta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2s2UsTF2eX1V2Q08qbJnQZuMEkOBdrkk',
    appId: '1:625640348358:ios:6956178711d82acc2b55c7',
    messagingSenderId: '625640348358',
    projectId: 'applacanasta',
    storageBucket: 'applacanasta.appspot.com',
    androidClientId: '625640348358-2oc1cv0oe4j7onvb6p769fot1f2f0gcg.apps.googleusercontent.com',
    iosClientId: '625640348358-masdiot74gnjvf4nlitgntg1a5rdb5lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.laCanasta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2s2UsTF2eX1V2Q08qbJnQZuMEkOBdrkk',
    appId: '1:625640348358:ios:4dec43c21e109e822b55c7',
    messagingSenderId: '625640348358',
    projectId: 'applacanasta',
    storageBucket: 'applacanasta.appspot.com',
    androidClientId: '625640348358-2oc1cv0oe4j7onvb6p769fot1f2f0gcg.apps.googleusercontent.com',
    iosClientId: '625640348358-m7pnbhsi58f6qiv9of36u947inijf9cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.laCanasta.RunnerTests',
  );
}
